import { AppShell, Flex, Header } from "@mantine/core";
import Head from "next/head";
import { ReactNode } from "react";
import ApplicationNavbar from "./navbar";
import {
  OrganizationSwitcher,
  RedirectToSignIn,
  UserButton,
  useAuth,
} from "@clerk/nextjs";

export type ApplicationLayoutProps = {
  children: ReactNode;
  title?: string;
};

const ApplicationLayout = (props: ApplicationLayoutProps) => {
  const { isSignedIn } = useAuth();

  if (!isSignedIn) {
    return (
      <>
        <RedirectToSignIn />
      </>
    );
  }

  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppShell
        padding="md"
        navbar={<ApplicationNavbar />}
        header={
          <Header height={55} p="xs">
            <Flex justify="space-between">
              <OrganizationSwitcher hidePersonal />
              <UserButton />
            </Flex>
            {/* Header content */}
          </Header>
        }
        styles={(theme) => ({
          main: {
            backgroundColor:
              theme.colorScheme === "dark"
                ? theme.colors.dark[8]
                : theme.colors.gray[0],
          },
        })}
      >
        <main>{props.children}</main>
      </AppShell>
    </>
  );
};

export default ApplicationLayout;
